title: Freespace
author:
  name: Yan
  email: me@maristie.com
description: >
  A personal website and irregularly updated technical blog.

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  social_links:
    linkedin: maristie
    github: maristie

  #skin: dark

theme: minima

# Enable pagination
#paginate: 30
#paginate_path: "/page/:num/"

# URL format
permalink: /:year/:month/:title

# Kramdown settings
kramdown:
    parse_block_html: true

# Default configuration for posts
defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post

# Exclude files
exclude:
    - LICENSE
    - CNAME

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Jekyll plugins
plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-redirect-from
    - jekyll-seo-tag
